apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: mongodb
  namespace: default
  annotations:
    description: "MongoDB admin credentials"
type: Opaque
data:
  # Replace 'root' and 'example' with your actual values, base64-encoded
  mongo-root-username: cm9vdA==  # base64 for 'root'
  mongo-root-password: ZXhhbXBsZQ==  # base64 for 'example'
