---
- name: install node and npm
  hosts: webserver
  tasks: 
  - name: Update apt repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: install nodejs and npm
    apt:
      pkg: 
       - nodejs
       - npm

- name: Create new Linux user for node app
  hosts: webserver
  tasks:
  - name: create new user
    user:
      name: nodeapp
      state: present
      group: admin
      shell: /bin/bash
      home: /home/nodeapp


- name: deploy node project
  hosts: webserver
  become: yes
  become_user: nodeapp
  tasks:
  - name: copy node project to webserver
    copy:
      src: /Users/sharon/nana/ansible/node_project/node_app/package/nodejs-app-1.0.0.tgz
      dest: /home/nodeapp/nodejs-app-1.0.0.tgz
  - name: extract node project
    unarchive:
      src: /home/nodeapp/nodejs-app-1.0.0.tgz
      dest: /home/nodeapp/
      remote_src: yes
  - name: install node project dependencies
    npm:
      path: /home/nodeapp/package
  - name: start node project
    command: node /home/nodeapp/package/app/server.js
    async: 600
    poll: 0
  - name: check node project status
    shell: ps aux | grep node
    register: app_status
  - debug: msg="{{ app_status.stdout_lines }}"



