---
- name: install node and npm
  hosts: webserver
  tasks: 
  - name: Update apt repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: install nodejs and npm
    apt:
      pkg: 
       - nodejs
       - npm

- name: Create new Linux user for node app
  hosts: webserver
  vars_files:
    - project-vars.yaml
  tasks:
    - name: create new user
      user:
         name: "{{ nodeapp_user }}"
         state: present
         group: admin
         shell: /bin/bash
         home: /home/nodeapp
      register: user_created_result

    - name: Display user creation result
      debug:
        msg: "{{ user_created_result }}"

    - name: Display created user's UID
      debug:
        msg: "The created user's UID is {{ user_created_result.uid }}"


- name: deploy node project
  hosts: webserver
  vars_files:
    - project-vars.yaml
  become: yes
  become_user: nodeapp
  tasks:
  - name: copy node project to webserver
    copy:
      src: "{{location}}/nodejs-app-{{version}}.tgz"
      dest: "{{destination}}/nodejs-app-{{version}}.tgz"
  - name: extract node project
    unarchive:
      src: "{{destination}}/nodejs-app-{{version}}.tgz"
      dest: "{{destination}}"
      remote_src: yes
  - name: install node project dependencies
    npm:
      path: "{{destination}}/package"
  - name: start node project
    command: node "{{destination}}/package/app/server.js"
    async: 600
    poll: 0
  - name: check node project status
    shell: ps aux | grep node
    register: app_status
  - debug: msg="{{ app_status.stdout_lines }}"



