---
- name: install node and npm
  hosts: webserver
  tasks: 
  - name: Update apt repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: install nodejs and npm
    apt:
      pkg: 
       - nodejs
       - npm


- name: deploy node project
  hosts: webserver
  tasks:
  - name: copy node project to webserver
    copy:
      src: /Users/sharon/nana/ansible/node_project/node_app/package/nodejs-app-1.0.0.tgz
      dest: /root/nodejs-app-1.0.0.tgz
  - name: extract node project
    unarchive:
      src: /root/nodejs-app-1.0.0.tgz
      dest: /root/
      remote_src: yes
  - name: install node project dependencies
    npm:
      path: /root/package
  - name: start node project
    command: node /root/package/app/server.js
    async: 600
    poll: 0


