---

- name: Update apt
  hosts: docker_server
  tasks: 
  - name: Update apt repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install pip for Python3
  hosts: docker_server
  tasks:
    - name: Install pip for Python3
      apt:
        name: python3-pip
        state: present

- name: install docker-compose plugin
  hosts: docker_server
  tasks:
    - name: Install docker-compose plugin
      pip:
        name: docker-compose
        state: present

- name: Install Python3
  hosts: docker_server
  tasks:
    - name: Install Python3
      apt:
        name: python3
        state: present

- name: Install Docker
  hosts: docker_server
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

- name: Test docker pull
  hosts: docker_server
  tasks:
    - name: Pull Docker image
      docker_image:
        name: redis
        source: pull

- name: Deploy Docker application
  hosts: docker_server
  tasks:
    - name: Run Docker Compose v2
      community.docker.docker_compose_v2:
        project_src: /Users/sharon/nana/docker/docker-compose.yaml
        state: present